application: transfarmr
version: 3
runtime: python27
api_version: 1
threadsafe: True


handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /.*
  script: main.app

- url: /send_to_backend
  script: test.app
  login: admin

# - url: .*backendscraping.* no, because they cannot be accessed externally, right? dammit.
#   script: test.app

# - url: /_ah/start maybe not needed when defining start script for specific backendin backends.yaml
#   script: test.py

# - url: /scrape
#   script: scrape.app
#   login: admin dette er for backends; veldig praktisk

# - url: /test
#   script: test.app
#   login: admin


libraries:
- name: jinja2
  version: latest 

- name: lxml
  version: latest
