application: transfarmr
version: 3
runtime: python27
api_version: 1
threadsafe: True


handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /send_to_backend
  script: main.app
  login: admin

- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest 

- name: lxml
  version: latest
